spring.application.name=blogApplication

spring.datasource.url= jdbc:mysql://localhost:3306/test_blog_website
spring.datasource.username= root
spring.datasource.password= Y1lm6z_S0nm3z_31

spring.jpa.hibernate.ddl-auto= update
